"""one to many rel

Revision ID: 638a35d7213a
Revises: 67eab18b2be4
Create Date: 2023-05-09 02:43:25.002030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638a35d7213a'
down_revision = '67eab18b2be4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id_parent', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id_parent'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id_parent')
    # ### end Alembic commands ###
